🗃️ repository:
  - .github/**
  - .gitignore
  - .gitattributes
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - scripts.yml
🛠️ build:
  - build/**
📀 app (client):
  - client/**
🦕 deploy:
  - deploy
🗺️ maps:
  - maps/(!sprites)/**
🎨 sprites:
  - maps/sprites/**
💿 app (server):
  - server/**
🧪 tests:
  - tests/**