contact_links:
  - name: 💡 Suggest new features
    url: https://github.com/lowlighter/gracidea/discussions/new?category=ideas
    about: Submit ideas to help us improve
  - name: 🙏 Request help
    url: https://github.com/lowlighter/gracidea/discussions/new?category=q-a
    about: Ask for help and support
  - name: 💬 Start a discussion
    url: https://github.com/lowlighter/gracidea/discussions/new?category=general
    about: Ask other questions related to this project here