name: 🌺
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        run: deno install --allow-all --name vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
      - name: Lint code
        run: vr lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        run: deno install --allow-all --name vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
      - name: Run tests
        run: vr test

  test-deploy:
    name: Run tests (deploy)
    runs-on: ubuntu-latest
  #  needs:
  #    - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor and deployctl
        run: |
          deno install --allow-all --name vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
          deno install --allow-all --name deployctl https://deno.land/x/deploy/deployctl.ts
      - name: Build data
        run: vr build --data
      - name: Build preview data
        if: github.event_name == 'pull_request'
        run: vr build --head ${{ github.actor }}:${{ github.head_ref }} --sha ${{ github.sha }}
      - name: Run tests
        run: deployctl check deploy/mod.ts
      - name: Publish preview data
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require("fs")
            await github.repos.createDispatchEvent({
              ...context.repo,
              event_type:"preview",
              client_payload:{
                sha:"${{ github.sha }}",
                issue_number:${{ github.event.number }},
                report:`${fs.readFileSync("diff/${{ github.sha }}.report")}`,
                diff:`${fs.readFileSync("diff/overworld_${{ github.sha }}_diff.json")}`,
              }
            })

  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
      - test-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor and dprint
        run: |
          deno install --allow-all --name vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> $GITHUB_PATH
      - name: Format code
        run: vr fmt
      - name: Bundle client app
        run: vr bundle
      - name: Build data and sprites
        run: vr build --all
      - name: Publish generated files
        run: |
          set +e
          git add --all
          git commit -m "Auto-build app"
          git push
          set -e
