name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        uses: jurassiscripts/setup-velociraptor@master
      - name: Run tests
        run: vr ci-test

  build:
    name: Build app
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        uses: jurassiscripts/setup-velociraptor@master
      - name: Build app
        run: vr ci-build
      - name: Publish generated files
        run: |
          set +e
          git config --global user.email "69689554+botlighter@users.noreply.github.com"
          git config --global user.name "botlighter"
          git add --all
          git commit -m "Auto-build app [skip ci]"
          git push
          set -e
