name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  # Run unit tests
  test: Unit tests
    name: Analyze code
    runs-on: ubuntu-latest
      steps:
        - name: Setup deno
          uses: denoland/setup-deno@main
        - name: Run tests
          run: deno test --unstable --allow-read

  # Run CodeQL on branch
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
          config-file: ./.github/config/codeql.yml
      - name: Analyze code
        uses: github/codeql-action/analyze@v1