name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        uses: jurassiscripts/setup-velociraptor@master
      - name: Run tests
        run: vr test

  build:
    name: Build app
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        uses: jurassiscripts/setup-velociraptor@master
      - name: Build app
        run: vr build
      - name: Publish generated files
        run: |
          set +e
          git status
          git add --update
          git commit -m "Auto-build app"
          git push
          set -e
