name: Label issues and pull requests
on:
  - pull_request_target
jobs:

  # Label
  label:
    name: Label issues and pull requests
    runs-on: ubuntu-latest

    steps:
      - name: Label issues and pull requests
        uses: actions/labeler@v2
        with:
          repo-token: "${{ github.token }}"
