name: 🗺️
on:
  - pull_request_target
jobs:

  preview:
    name: Build preview data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        run: deno install --allow-all --name vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
      - name: Build patches
        run: vr build --patch --head ${{ github.actor }}:${{ github.head_ref }} --sha ${{ github.sha }}
      - name: Checkout patches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: patches
      - name: Publish generated files
        run: |
          set +e
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add patches
          git commit -m "Auto-build patch ${{ github.sha }}"
          git push
          set -e
      - name: Publish report
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require("fs")
            await github.issues.createComment({
              ...context.repo,
              issue_number:${{ github.event.number }},
              body:`${fs.readFileSync("patches/${{ github.sha }}.report")}`,
            })