name: 🗺️
on:
  repository_dispatch:
    types:
      - preview
jobs:

  preview:
    name: Build preview data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish generated files
        run: |
          git status
          git checkout ci-attachments
          echo '${{ github.event.client_payload.patch }}' > patches/${{ github.event.client_payload.sha }}.json
          git add --all
          git commit -m "Auto-build patch ${{ github.event.client_payload.sha }}"
          git push
      - name: Publish report
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require("fs")
            await github.issues.createComment({
              ...context.repo,
              issue_number:${{ github.event.client_payload.issue_number }},
              body:github.event.client_payload.report,
            });