name: 🗺️
on:
  - pull_request_target
jobs:

  preview:
    name: Build preview data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
      - name: Setup velociraptor
        run: deno install --allow-all --name vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
      - run: |
          git status
      - name: Build data diff
        run: |
          vr build --data
          vr build --head ${{ github.actor }}:${{ github.head_ref }} --sha ${{ github.sha }}
      - name: Publish generated files
        run: |
          git fetch origin/ci-attachments
          git switch ci-attachments
          git status
          git add diff
          git commit -m "Auto-build diff ${{ github.sha }}"
          git push
      - name: Publish report
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require("fs")
            await github.issues.createComment({
              ...context.repo,
              issue_number:${{ github.event.number }},
              body:`${fs.readFileSync("diff/${{ github.sha }}.report")}`,
            });