name: 🗺️
on:
  repository_dispatch:
    types:
      - Build preview
jobs:

  preview:
    name: Build preview data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: patches
      - name: Publish generated files
        run: |
          set +e
          mkdir -p patches
          echo '${{ github.event.client_payload.patch }}' > patches/${{ github.event.client_payload.sha }}.json
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "Auto-build patch ${{ github.event.client_payload.sha }}"
          git push
          set -e
      - name: Publish report
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require("fs")
            await github.issues.createComment({
              ...context.repo,
              issue_number:${{ github.event.client_payload.issue_number }},
              body:'${{ github.event.client_payload.report }}',
            });
